apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user
  labels:
    app: udagram-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-user
  template:
    metadata:
      labels:
        app: udagram-user
    spec:
      containers:
      - name: udagram-user
        image: ricardiles/udagram-user
        env:
        - name: POSTGRES_USERNAME
          value: "rardiles"
        - name: POSTGRES_PASSWORD
          value: "udacity123.."
        - name: POSTGRES_HOST
          value: "udacity-dev.c4k86qizidvt.us-west-2.rds.amazonaws.com"
        - name: POSTGRES_DB
          value: "postgres"
        - name: AWS_BUCKET
          value: "udacity-229318163752-dev"
        - name: AWS_REGION
          value: "us-west-2"
        - name: AWS_PROFILE
          value: "default"
        - name: JWT_SECRET
          value: "helloudacity"
        - name: URL
          value: "http://udagram-user:8080"
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 80