apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feeds-app
  labels:
    app: udagram-feeds-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-feeds-app
  template:
    metadata:
      labels:
        app: udagram-feeds-app
    spec:
      containers:
      - name: udagram-feeds
        image: ricardiles/udagram-feeds
        env:
        - name: POSTGRES_USERNAME
          value: "rardiles"
        - name: POSTGRES_PASSWORD
          value: "udacity123.."
        - name: POSTGRES_HOST
          value: "udacity-dev.c4k86qizidvt.us-west-2.rds.amazonaws.com"
        - name: POSTGRES_DB
          value: "postgres"
        - name: AWS_BUCKET
          value: "udacity-229318163752-dev"
        - name: AWS_REGION
          value: "us-west-2"
        - name: AWS_PROFILE
          value: "default"
        - name: JWT_SECRET
          value: "helloudacity"
        - name: URL
          value: "http://a837364d12ec849cebeb60deac693df3-1142491214.us-west-2.elb.amazonaws.com:4200/"
        - name: PORT
          value: "8081"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m" 
        ports:
        - containerPort: 8081