apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-app
  labels:
    run: udagram-frontend-app
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    run: udagram-frontend-app